version: '3.8'

services:
  streamlit:
    image: summarize-my-document-frontend
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "8501:8501"
    environment:
      - AWS_REGION=us-west-2
      - BACKEND_URL=https://summarize-my-document-backend.liguori.people.aws.dev
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=1
    volumes:
      - type: bind
        source: ~/.aws
        target: /root/.aws
